name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

variables:
  # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  # Improve performance by not sending telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'

trigger:
  branches:
    include:
      - master

jobs:
- job: Win2019
  displayName: Windows Server 2019
  pool:
    vmImage: windows-2019
  steps:
  - template: templates/ci-general.yml

- job: macOS
  displayName: macOS 10.15
  pool:
    vmImage: macOS-10.15
  steps:
  - template: templates/ci-general.yml

- job: Ubuntu
  displayName: Ubuntu 20.04
  pool:
    vmImage: Ubuntu-20.04
  steps:
  - template: templates/ci-general.yml
